[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && npm install && cd packages/types && npm run build && cd ../../apps/api && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

